#!/bin/sh
# <!-- **************************************  -->
# <!-- Don't Remove this Disclaimer            -->
# <!-- **************************************  -->
echo
echo "*****************************************"
echo "*  Uninstall AdvancedScreenshot Plugin   *"
echo "*****************************************"

EXTDIR="/usr/lib/enigma2/python/Plugins/Extensions/AdvancedScreenshot"

if [ -d "$EXTDIR" ]; then
   rm -rf "$EXTDIR" > /dev/null 2>&1
fi

echo "*****************************************"
echo "*          ....done                     *"
echo "*****************************************"
exit 0


